const portfolioProjectsDate = [
  {
    id: 1,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/Ci5bR2i.png",
    type: "web",
  },
  {
    id: 2,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/hbN1rUK.png",
    type: "web",
  },
  {
    id: 3,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "web",
  },
  {
    id: 4,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/3BQH36M.png",
    type: "web",
  },
  {
    id: 5,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/mIWV2OU.png",
    type: "web",
  },
  {
    id: 6,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "web",
  },
  {
    id: 7,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/mIWV2OU.png",
    type: "web",
  },
  {
    id: 8,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "web",
  },
  {
    id: 9,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/mIWV2OU.png",
    type: "web",
  },
  {
    id: 10,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "app",
  },
  {
    id: 11,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/hbN1rUK.png",
    type: "app",
  },
  {
    id: 12,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "app",
  },
  {
    id: 13,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/3BQH36M.png",
    type: "app",
  },
  {
    id: 14,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "app",
  },
  {
    id: 15,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "ui",
  },
  {
    id: 16,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/Ci5bR2i.png",
    type: "desing",
  },
  {
    id: 17,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "desing",
  },
  {
    id: 18,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "desing",
  },
  {
    id: 19,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/hbN1rUK.png",
    type: "desing",
  },
  {
    id: 20,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "ui",
  },
  {
    id: 21,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://files.sbcdnsb.com/images/G-fSAmDAflRspM5kyaEm1g/businesses/1630498082/KMMlogo-withbackground0.png",
    type: "ui",
  },
  {
    id: 22,
    name: "Business Card Desing",
    text: "UI/UX Design",
    img: "https://imgur.com/hbN1rUK.png",
    type: "ui",
  },
];

export default portfolioProjectsDate;
